PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?class WHERE {
  { ?class a owl:Class }
  UNION
  { ?class rdfs:subClassOf* owl:Thing }
  FILTER(STRSTARTS(STR(?class), "https://rmagro.org/ontology/"))
}
