name: Build Linked Data Exports

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Apache Jena and ROBOT
      run: |
        wget -O apache-jena.tar.gz https://downloads.apache.org/jena/binaries/apache-jena-5.3.0.tar.gz
        tar -xzf apache-jena.tar.gz
        wget -O robot.jar https://github.com/ontodev/robot/releases/latest/download/robot.jar

    - name: Convert TTL to all formats (using Apache Jena riot)
      run: |
        mkdir -p dist/full
        ./apache-jena-5.3.0/bin/riot --output=RDF/XML ontology.ttl > dist/full/ontology.rdf
        ./apache-jena-5.3.0/bin/riot --output=JSON-LD ontology.ttl > dist/full/ontology.jsonld
        ./apache-jena-5.3.0/bin/riot --output=N-Triples ontology.ttl > dist/full/ontology.nt
        ./apache-jena-5.3.0/bin/riot --output=N3 ontology.ttl > dist/full/ontology.n3

    - name: Extract concepts and convert formats
      run: |
        mkdir -p dist/concepts

        java -jar robot.jar query \
          --input ontology.ttl \
          --query queries/get-classes.rq \
          --csv class_list.csv

        tail -n +2 class_list.csv | sed 's|https://rmagro.org/ontology/||' > concept_names.txt
        cat concept_names.txt

        for concept in $(cat concept_names.txt); do
          echo "Processing concept: $concept"
          echo "https://rmagro.org/ontology/$concept" > temp_concept.txt

          java -jar robot.jar extract \
            --input ontology.ttl \
            --method STAR \
            --term-file temp_concept.txt \
            --output "dist/concepts/${concept}.ttl" \
            --format turtle

          ./apache-jena-5.3.0/bin/riot --output=RDF/XML "dist/concepts/${concept}.ttl" > "dist/concepts/${concept}.rdf"
          ./apache-jena-5.3.0/bin/riot --output=JSON-LD "dist/concepts/${concept}.ttl" > "dist/concepts/${concept}.jsonld"
          ./apache-jena-5.3.0/bin/riot --output=N-Triples "dist/concepts/${concept}.ttl" > "dist/concepts/${concept}.nt"

          rm temp_concept.txt
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linked-data-exports
        path: dist

    - name: Commit dist folder to repository
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Update Linked Data exports'
        add: 'dist/*'
