name: Build Linked Data Exports
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Convert TTL to all formats (using Docker)
      run: |
        mkdir -p dist
        
        echo "Converting ontology.ttl to RDF/XML"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=RDF/XML /data/ontology.ttl > dist/ontology.rdf
        
        echo "Converting ontology.ttl to JSON-LD"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=JSON-LD /data/ontology.ttl > dist/ontology.jsonld
        
        echo "Converting ontology.ttl to N-Triples"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=N-Triples /data/ontology.ttl > dist/ontology.nt
        
        echo "Converting ontology.ttl to N3"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=N3 /data/ontology.ttl > dist/ontology.n3
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linked-data-exports
        path: dist
    
    - name: Commit dist folder to repository
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Update Linked Data exports'
        add: 'dist/*'
