name: Build Linked Data Exports
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Apache Jena (for all conversions)
      run: |
        # Try multiple mirrors with retry logic
        for mirror in \
          "https://downloads.apache.org/jena/binaries/apache-jena-5.3.0.tar.gz" \
          "https://archive.apache.org/dist/jena/binaries/apache-jena-5.3.0.tar.gz" \
          "https://www.apache.org/dyn/closer.lua/jena/binaries/apache-jena-5.3.0.tar.gz?action=download"; do
          echo "Trying to download from: $mirror"
          if wget --timeout=30 --tries=3 "$mirror" -O apache-jena-5.3.0.tar.gz; then
            echo "Download successful from: $mirror"
            break
          else
            echo "Failed to download from: $mirror"
          fi
        done
        
        if [ ! -f apache-jena-5.3.0.tar.gz ]; then
          echo "All download attempts failed"
          exit 1
        fi
        
        tar -xzf apache-jena-5.3.0.tar.gz
    - name: Convert TTL to all formats (using Apache Jena riot)
      run: |
        mkdir -p dist
        echo "Converting ontology.ttl to RDF/XML"
        ./apache-jena-5.3.0/bin/riot --output=RDF/XML ontology.ttl > dist/ontology.rdf
        echo "Converting ontology.ttl to JSON-LD"
        ./apache-jena-5.3.0/bin/riot --output=JSON-LD ontology.ttl > dist/ontology.jsonld
        echo "Converting ontology.ttl to N-Triples"
        ./apache-jena-5.3.0/bin/riot --output=N-Triples ontology.ttl > dist/ontology.nt
        echo "Converting ontology.ttl to N3"
        ./apache-jena-5.3.0/bin/riot --output=N3 ontology.ttl > dist/ontology.n3
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linked-data-exports
        path: dist
    - name: Commit dist folder to repository
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Update Linked Data exports'
        add: 'dist/*'
