name: Build Linked Data Exports

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Convert TTL to all formats
      run: |
        mkdir -p dist/full
        
        # Convert the full ontology to different formats
        echo "Converting full ontology.ttl to RDF/XML"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=RDF/XML /data/ontology.ttl > dist/full/ontology.rdf
        
        echo "Converting full ontology.ttl to JSON-LD"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=JSON-LD /data/ontology.ttl > dist/full/ontology.jsonld
        
        echo "Converting full ontology.ttl to N-Triples"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=N-Triples /data/ontology.ttl > dist/full/ontology.nt
        
        echo "Converting full ontology.ttl to N3"
        docker run --rm -v $(pwd):/data stain/jena:latest riot --output=N3 /data/ontology.ttl > dist/full/ontology.n3
        
        echo "Conversion complete. Generated files:"
        find dist/ -name "*.ttl" -o -name "*.rdf" -o -name "*.jsonld" -o -name "*.nt" | sort
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linked-data-exports
        path: dist
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update Linked Data exports'
        title: 'Auto-update: Linked Data exports'
        body: |
          Automated update of Linked Data exports:
          - ontology.rdf (RDF/XML)
          - ontology.jsonld (JSON-LD) 
          - ontology.nt (N-Triples)
          - ontology.n3 (N3)
        branch: update-linked-data-exports
        delete-branch: true
